#!/usr/bin/env ruby
# Author:: Lori Holden (http://loriholden.com)
# Copyright:: Copyright (c) 2008 Lori Holden
# License:: This code is free to use under the terms of the MIT license.

require 'lib/presentation'

Presentation.build